name: Tests

on:
  push:
  pull_request:
    branches:
      - master
      - main

jobs:

  shunit2_tests:
    name: shUnit2 test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test-script:
          - tests/test_check_tcp4_connection_established.sh
          - tests/test_check_tcp4_socket_listening.sh
          - tests/test_get_ipv4.sh
    
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Install shUnit2
        run: git clone -b v2.1.8 https://github.com/kward/shunit2.git /opt/shunit2
      - 
        name: Run ${{ matrix.test-script }}
        run: ./${{ matrix.test-script }}
