name: Tests

on:
  push:
  pull_request:
    branches:
      - master
      - main

jobs:

  test_helpers_get_ipv4:
    name: Test helpers/get_ipv4.sh
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Run Test
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./tests/test_get_ipv4.Dockerfile.debian
          no-cache: true
          push: false
          
  test_checks_check_tcp4_connection_established:
    name: Test checks/check_tcp4_connection_established.sh
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Build test image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./tests/test_check_tcp4_connection_established.Dockerfile.debian
          no-cache: true
          push: false
          tags: test_check_tcp4_connection_established
      -
        name: Run test
        run: |
          docker network create testnet
          docker run --rm -d -i --name redis --network testnet --entrypoint redis-server redis
          docker run --rm -d -i --name test_check_tcp4_connection_established --network testnet test_check_tcp4_connection_established
          docker exec -i bash -x /workdir/checks/check_tcp4_connection_established.sh
          docker kill test_check_tcp4_connection_established
          docker kill redis
          