name: Tests

on:
  push:
  pull_request:
    branches:
      - master
      - main

jobs:
  tests:
    name: Test helpers/get_ipv4.sh
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Run Test
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./tests/test_get_ipv4.Dockerfile.debian
          no-cache: true
          push: false
